image: busybox

pages:
  tags:
    - docker
  script:
    - cp -r static/html public
    - cp -r static/build public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "gitlab-ci"

